<option value="">Selecione</option>
<option value="N0">N0</option>
<option value="N1">N1</option>
<option value="N2">N2</option>
<option value="N3">N3</option>
<option value="N4">N4</option>
<option value="AVARIA">AVARIA</option>
<option value="OK A-">OK A-</option>
<option value="CRIPPLE">CRIPPLE</option>